/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sbvezjqtvycsxhgsvgfc"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNidmV6anF0dnljc3hoZ3N2Z2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0NjYxMTYsImV4cCI6MjA4OTA0MjExNn0.QS8-g-BfMwn7-C7hPLIlWITe1qtrmr31KqWQKdz-KC0"